<script src="{{ asset('lib/jalalidatepicker.min.js') }}"></script>
<script>
(()=>{const container=document.querySelector('#customers-container'),template=document.querySelector('#customer-template');if(!container)return;let datepickerStarted=false;
const startDatepicker=()=>{if(!datepickerStarted&&typeof window.jalaliDatepicker!=='undefined'){window.jalaliDatepicker.startWatch({time:false,autoHide:true,separatorChars:{date:'/'}});datepickerStarted=true}};
const clearSection=(section)=>section.querySelectorAll('input,select,textarea').forEach(el=>{if(el.type==='radio'||el.type==='checkbox')el.checked=false;else el.value=''});
const sync=card=>{const checked=card.querySelector('[name$="[purchase_status]"]:checked');card.dataset.status=checked?.value||''};
const renumber=()=>container.querySelectorAll('.customer-card').forEach((card,i)=>{card.dataset.index=i;card.querySelector('.customer-number').textContent=i+1;card.querySelector('.remove-customer').classList.toggle('d-none',i===0);card.querySelectorAll('[name]').forEach(el=>el.name=el.name.replace(/^customers\[\d+]/,`customers[${i}]`))});
container.addEventListener('change',e=>{if(e.target.matches('[name$="[purchase_status]"]')){const card=e.target.closest('.customer-card');clearSection(card.querySelector(e.target.value==='purchased'?'.non-buyer-section':'.buyer-section'));sync(card)}});
container.addEventListener('click',e=>{const trigger=e.target.closest('.cs-date-trigger');if(trigger){const input=trigger.closest('.cs-date-field')?.querySelector('.cs-jalali-date');if(input&&typeof window.jalaliDatepicker!=='undefined')window.jalaliDatepicker.show(input);return}const b=e.target.closest('.remove-customer');if(b){b.closest('.customer-card').remove();renumber()}});
container.addEventListener('paste',e=>{if(e.target.matches('.cs-jalali-date'))e.preventDefault()});container.addEventListener('drop',e=>{if(e.target.matches('.cs-jalali-date'))e.preventDefault()});
document.querySelector('#add-customer-btn')?.addEventListener('click',()=>{const nextIndex=container.children.length;container.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',nextIndex).replaceAll('__INDEX_DISPLAY__',nextIndex+1));renumber();startDatepicker()});
const searchUrl=@json(route('customer-satisfaction-forms.customer-search'));const searchStates=new WeakMap();
const resetCustomer=card=>{const state=searchStates.get(card);state?.controller?.abort();const id=card.querySelector('.customer-id'),name=card.querySelector('.customer-name'),phone=card.querySelector('.customer-phone'),summary=card.querySelector('.selected-customer');id.value='';name.value='';phone.value='';name.readOnly=false;phone.readOnly=false;summary.classList.add('d-none');summary.querySelector('.selected-details').textContent='';};
const message=(box,text)=>{box.replaceChildren();const item=document.createElement('div');item.className='p-3 text-muted';item.textContent=text;box.append(item);box.classList.remove('d-none')};
const renderResults=(card,items)=>{const box=card.querySelector('.customer-search-results');box.replaceChildren();if(!items.length){message(box,'مشتری پیدا نشد');return}items.forEach(customer=>{const button=document.createElement('button');button.type='button';button.className='customer-result';button._customer=customer;[customer.name,`${customer.phone||'—'} — کد مشتری: ${customer.customer_number||'—'}`,customer.city?`شهر: ${customer.city}`:null,`فروشنده/ویزیتور: ${customer.seller_name}`].filter(Boolean).forEach((line,i)=>{const el=document.createElement(i?'small':'strong');el.className='d-block';el.textContent=line;button.append(el)});box.append(button)});box.classList.remove('d-none')};
container.addEventListener('input',e=>{if(!e.target.matches('.customer-search'))return;const card=e.target.closest('.customer-card'),box=card.querySelector('.customer-search-results'),query=e.target.value.trim();if(card.querySelector('.customer-id').value)resetCustomer(card);let state=searchStates.get(card)||{};clearTimeout(state.timer);state.controller?.abort();if(query.length<2){box.classList.add('d-none');searchStates.set(card,state);return}state.timer=setTimeout(async()=>{state.controller=new AbortController();message(box,'در حال جست‌وجو...');try{const response=await fetch(`${searchUrl}?q=${encodeURIComponent(query)}`,{headers:{Accept:'application/json'},signal:state.controller.signal});if(!response.ok)throw new Error();renderResults(card,await response.json())}catch(error){if(error.name!=='AbortError')message(box,'خطا در جست‌وجو؛ دوباره تلاش کنید.')}},350);searchStates.set(card,state)});
container.addEventListener('click',e=>{const result=e.target.closest('.customer-result');if(result){const card=result.closest('.customer-card'),c=result._customer;card.querySelector('.customer-id').value=c.id;card.querySelector('.customer-name').value=c.name||'';card.querySelector('.customer-phone').value=c.phone||'';card.querySelector('.customer-name').readOnly=true;card.querySelector('.customer-phone').readOnly=true;card.querySelector('.customer-search').value=c.name||'';const details=card.querySelector('.selected-details');details.textContent='';[`نام مشتری: ${c.name||'—'}`,`شماره تماس: ${c.phone||'—'}`,`کد مشتری: ${c.customer_number||'—'}`,`شهر: ${c.city||'—'}`,`فروشنده/ویزیتور: ${c.seller_name}`].forEach(line=>{details.append(document.createTextNode(line),document.createElement('br'))});card.querySelector('.selected-customer').classList.remove('d-none');card.querySelector('.customer-search-results').classList.add('d-none');return}const change=e.target.closest('.change-customer');if(change){const card=change.closest('.customer-card');resetCustomer(card);const input=card.querySelector('.customer-search');input.value='';input.focus()}});
document.addEventListener('click',e=>{if(!e.target.closest('.customer-search-wrap'))document.querySelectorAll('.customer-search-results').forEach(el=>el.classList.add('d-none'))});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.customer-search-results').forEach(el=>el.classList.add('d-none'))});
container.querySelectorAll('.customer-card').forEach(sync);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startDatepicker,{once:true});else startDatepicker()})();
</script>
